[colors.primary]
background = "#101010"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
y = 2

[[keyboard.bindings]]
chars = "\b"
key = "Back"

[scrolling]
history = 100000

[window]
opacity = 0.8
